### ISSUE TITLE
How many episodes from the HM3D dataset did you use for testing?

### ISSUE THREAD

**Issue by zhai-create** [wzcai99/Pixel-Navigator#10]
I would like to confirm how many episodes from "HM3D-v2.val" you used for testing. Is the number of test episodes set to 200 in the code?

**Comment by wzcai99** [comment]
We use 1000 episodes to test the performance. The default parameters is set to 200 in the code considering the cost of GPT4V api.

**Comment by zhai-create** [comment]
Ok, is there any difference in the val data between HM3D v0.1 and v0.2 versions? I noticed that some of the test results for comparison algorithms in your paper were obtained on v0.1, such as ZSON.

**Comment by zhai-create** [comment]
Meanwhile, what is your success distance, 1m?

**Comment by wzcai99** [comment]
The main difference is that the v2 add more scenes for testing.  The v2 version contains 36 val scenes and the v1 version contains 20 val scenes.

**Comment by wzcai99** [comment]
Yes, 1m to the target objects.

**Comment by zhai-create** [comment]
Thank you!
