### ISSUE TITLE
Unable to test objnav_benchmark.py

### ISSUE THREAD

**Issue by Athirakr94** [wzcai99/Pixel-Navigator#11]
Dear Authors,
The work seems to be interesting and wanted try this out. To start I have followed the commands in the repo. I am able to use mp3d in policy evaluation it works. But with this command, python objnav_benchmark.py --checkpoint=/home/athira/Pixel-Navigator/checkpoints/pixelnav_C.ckpt
I am getting error. Screen shot shared for reference. The val split of hm3d dataset is downloaded to /data/athira/hm3d
![image](https://github.com/user-attachments/assets/ef3e09e2-f732-44de-9d0b-ac465e2da680)
Please help.

**Comment by Athirakr94** [comment]
That was a path issue I could resolve that error. But now a new index error is coming.
![image](https://github.com/user-attachments/assets/d5774c58-8fc2-41d0-8a54-1ead03e66a44)
Any idea

**Comment by wzcai99** [comment]
Hi, I checked my code and remember that I comment one line of the habitat-lab code, which is in the line 106 of the habitat-lab/habitat-lab/habitat/core/env.py. It seems that only comments this line can make the scene_dataset_config path correct. Maybe there should be a better way to solve this.
![image](https://github.com/user-attachments/assets/b06a1728-b0a6-42af-b7f8-5cb8f33c5ecd)

**Comment by wzcai99** [comment]
And you can try whether this can solve your problem @Athirakr94.

**Comment by Athirakr94** [comment]
Thanks I tried commenting line 106, but then its throwing a validation error as,
raise ValidationError("Cannot convert '$VALUE_TYPE' to string: '$VALUE'")
omegaconf.errors.ValidationError: Cannot convert 'tuple' to string: '()'
    full_key: habitat.simulator.scene_dataset
    reference_type=SimulatorConfig
    object_type=SimulatorConfig
So tried commenting lines 105-107, then old error is coming again
![Uploading image.png…]()

**Comment by wzcai99** [comment]
Sorry, I cannot see the recent uploaded image, can you upload the error message again?

**Comment by Athirakr94** [comment]
Thanks for the help I was able to run the script after ensuring draw_goal_aabbs=False. Hope this is fine
