### ISSUE TITLE
When will the code for the pixel navigation module be open-sourced?

### ISSUE THREAD

**Issue by xiyuying** [wzcai99/Pixel-Navigator#4]
When will the code for the pixel navigation module be open-sourced?My email address is:2428558354@qq.com

**Comment by zhangpingrui** [comment]
> When will the code for the pixel navigation module be open-sourced?My email address is:[2428558354@qq.com](mailto:2428558354@qq.com)

Have you got the whole code?  I am also interested in this work.

**Comment by wzcai99** [comment]
The code for the pixel-nav skill will be available around June after ICRA. Thank you for all your interests in our project.

**Comment by xiyuying** [comment]
Great,！thank you for your reply.



发自我的iPhone


------------------ Original ------------------
From: wzcai99 ***@***.***&gt;
Date: Sun,Apr 7,2024 5:48 PM
To: wzcai99/Pixel-Navigator ***@***.***&gt;
Cc: xiyuying ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [wzcai99/Pixel-Navigator] When will the code for the pixelnavigation module be open-sourced? (Issue #4)





 
The code for the pixel-nav skill will be available around June after ICRA. Thank you for all your interests in our project.

**Comment by zhangpingrui** [comment]
> The code for the pixel-nav skill will be available around June after ICRA. Thank you for all your interests in our project.

Thanks for your reply!

**Comment by wzcai99** [comment]
We just released the code and feel free to ask for any further questions.
