### ISSUE TITLE
Release of dataset generation code

### ISSUE THREAD

**Issue by FlightVin** [wzcai99/Pixel-Navigator#6]
Hi,

I was wondering if I could have the code that you folks used to **_create the dataset used for training the network_**. 
However, if that cannot be provided at the moment, could I have pointers as to how can I hack the code for the episodes generated in the [evaluation](https://github.com/wzcai99/Pixel-Navigator/blob/master/evaluate_policy.py) for this purpose?

Thanks!

**Comment by wzcai99** [comment]
Sorry, for some reason, we currently cannot provide the detailed data generation code. But one tip to generate the navigation trajectories is using the class ShortestPathFollower() defined in the habitat-lab.

**Comment by FlightVin** [comment]
In #7, it has been mentioned that the training is done over batches. Are you ensuring that each trajectory is exactly 64 timesteps long? 

If not, how are you calculating the loss over the batch?

**Comment by wzcai99** [comment]
No, it is common for the trajectories not to be 64 time steps long. However, when doing the training, we will provide a mask indicating the trajectory length for every batch of trajectories. For example, with a trajectory of 5 timesteps, the mask would be [1,1,1,1,1,0,0...]. And the loss would be the average error of the first 5 timestep predictions.

**Comment by xiyuying** [comment]
> 你好，
> 
> 我想知道我是否可以得到你们用来**_创建用于训练网络的数据集_**的代码。 但是，如果目前无法提供，我是否可以指点一下如何破解评估中生成的情节的代码[以](https://github.com/wzcai99/Pixel-Navigator/blob/master/evaluate_policy.py)达到此目的？
> 
> 谢谢！

Hello, may I ask if you encountered the following error when running `objnav_benchmark.py`?
File "/home/xi/code/Pixel-Navigator-master/objnav_benchmark.py", line 60, in <module>
    obs = habitat_env.reset()
  File "/home/xi/habitat-lab/habitat-lab/habitat/core/env.py", line 264, in reset
    self._task.measurements.reset_measures(
  File "/home/xi/habitat-lab/habitat-lab/habitat/core/embodied_task.py", line 166, in reset_measures
    measure.reset_metric(*args, **kwargs)
  File "/home/xi/habitat-lab/habitat-lab/habitat/tasks/nav/nav.py", line 861, in reset_metric
    self._draw_goals_aabb(episode)
  File "/home/xi/habitat-lab/habitat-lab/habitat/tasks/nav/nav.py", line 772, in _draw_goals_aabb
    sem_scene.objects[object_id].id.split("_")[-1]
IndexError: list index out of range

**Comment by xiyuying** [comment]
> Hi,
> 
> I was wondering if I could have the code that you folks used to **_create the dataset used for training the network_**. However, if that cannot be provided at the moment, could I have pointers as to how can I hack the code for the episodes generated in the [evaluation](https://github.com/wzcai99/Pixel-Navigator/blob/master/evaluate_policy.py) for this purpose?
> 
> Thanks!

Hello, may I ask if you encountered the following error when running objnav_benchmark.py?
If so, how did you resolve it?Thank you

File "/home/xi/code/Pixel-Navigator-master/objnav_benchmark.py", line 60, in
obs = habitat_env.reset()
File "/home/xi/habitat-lab/habitat-lab/habitat/core/env.py", line 264, in reset
self._task.measurements.reset_measures(
File "/home/xi/habitat-lab/habitat-lab/habitat/core/embodied_task.py", line 166, in reset_measures
measure.reset_metric(*args, **kwargs)
File "/home/xi/habitat-lab/habitat-lab/habitat/tasks/nav/nav.py", line 861, in reset_metric
self._draw_goals_aabb(episode)
File "/home/xi/habitat-lab/habitat-lab/habitat/tasks/nav/nav.py", line 772, in draw_goals_aabb
sem_scene.objects[object_id].id.split("")[-1]
IndexError: list index out of range

**Comment by FlightVin** [comment]
Hi, I've not attempted to load the data exactly in their format. So, I'm afraid I can't answer your question as I didn't get this error

**Comment by xiyuying** [comment]
> Hi, I've not attempted to load the data exactly in their format. So, I'm afraid I can't answer your question as I didn't get this error

OK，Thank you!

**Comment by wzcai99** [comment]
@xiyuying Maybe you are using the HSSD dataset? I think I also encountered the same problem. See this [issue](https://github.com/facebookresearch/habitat-lab/issues/1920).

**Comment by xiyuying** [comment]
> @xiyuying Maybe you are using the HSSD dataset? I think I also encountered the same problem. See this [issue](https://github.com/facebookresearch/habitat-lab/issues/1920).

Thank you for your response. The link you provided does indeed solve the problem. Additionally, changing `draw_goal_aabbs=True` to `False` in `config_utils.py` also seems to resolve the issue, although I haven't figured out the reason why.
