### ISSUE TITLE
Regarding the experimental section of the paper

### ISSUE THREAD

**Issue by liaokaiyao** [wzcai99/Pixel-Navigator#9]
HI，I have some doubts about the experimental setup. Isn't the long-horizon navigation tasks mentioned in the article that the target object is invisible at the beginning? In that case, you should start by selecting an object in the scene for navigation instead of choosing the first RGB frame pixel as the target? Just like the bottom of your Figure 5.

**Comment by wzcai99** [comment]
Well, the pixel navigation policy is only a **local navigation policy** that can understand the pixel as a goal specification. And yes, in most cases, the object navigation target should be invisible. Therefore, to make the local navigation policy finish the long-horizon tasks, we need a planner to select the intermediate pixel goals. In our method, the intermediate pixel goals are the center point of the **floor** segmentation, which can lead the agent to travel between different rooms. Only when the agent can detect the target object, the goal pixel will be assigned as the center of the target segmentation.

**Comment by liaokaiyao** [comment]
I understand your method, I just don't quite understand why your experimental setup is not an object
![image](https://github.com/user-attachments/assets/40d11319-4a96-40a0-9312-0fdac334040c)

**Comment by wzcai99** [comment]
Sometimes the object can be very big, like the floor, and different pixels represent different locations, by randomly selecting we can evaluate the local navigation policy capability more fairly.

**Comment by liaokaiyao** [comment]
But in that case, you won't be able to evaluate your navigation ability for initially invisible items

**Comment by wzcai99** [comment]
Yes, therefore in the paper we evaluate the HM3D object-navigation benchmark results.

**Comment by liaokaiyao** [comment]
I'm sorry, I didn't see clearly that PIXnav task and object nav task are not the same.

**Comment by liaokaiyao** [comment]
I'm sorry, I didn't see clearly that PIXnav task and object nav task are not the same. Thank you for your answer.
